---
# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account following like this:
apiVersion: v1
kind: ServiceAccount
metadata:
   name: metaflow-deployment-service-account # 
   namespace: metaflow-deployments     # From metaflow-cluster-core-namespaces.yml . Segregated so that cluster access for metaflow deployments only get privilages to spawn clusters. 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects: # This will change with a namespace deployment. 
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: metaflow-deployment-service-account
    # Reference to upper's `metadata.namespace`
    namespace: metaflow-deployments
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io