apiVersion: batch/v1
kind: Job
metadata:
  name: GPU-Job
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:9.1-devel
    terminationMessagePath: "/tmp/my-log"
    resources:
        limits:
            memory: 4089Mi
            # ^ Set memory in case default limits are set low
            nvidia.com/gpu: 1 # requesting 1 GPUs
            # ^ For Legacy Accelerators mode this key must be renamed
            #   'alpha.kubernetes.io/nvidia-gpu'
  tolerations:
    # This toleration will allow the gpu hook to run anywhere
    #   By default this is permissive in case you have tainted your GPU nodes.
    - operator: "Exists"        # ^ If you have a specific taint to target, comment out the above and modify
    #   the example belowcuda-container
